- name: Collect all containers
  ansible.builtin.set_fact:
    _containers: >
        {{
          ([c8s_container] if c8s_container is defined else []) +
          ( c8s_containers if c8s_containers is defined else []) +
          ( c8s_project.containers if c8s_project.containers is defined else [])
        }}

- name: Ensure that the containers are present
  containers.podman.podman_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: "present"
  # become: true
  when:
    - item.name is defined
    - item.image is defined
  loop: "{{ _containers }}"
  loop_control:
    label: "{{ item.name }}"

- name: Set 
  ansible.builtin.include_tasks: container-mgmt.yml