- ansible.builtin.set_fact:
    _networks: >
        {{
          ([c8s_network] if c8s_network is defined else []) +
          ( c8s_networks if c8s_networks is defined else []) +
          ( c8s_project.networks if c8s_project.networks is defined else [])
        }}

- name: "Ensure that the networks are present"
  containers.podman.podman_network:
    name: "{{ item.name }}"
    internal: "{{ item.internal | default(false) }}"
    ip_range: "{{ item.ip_range | default(omit) }}"
    subnet: "{{ item.subnet | default(omit) }}"
    gateway: "{{ item.gateway | default(omit) }}"
    state: "present"
  # become: true
  when: 
    - item.name is defined
  loop: "{{ _networks }}"
  loop_control:
    label: "{{ item.name }}"


