- name: "Clean DSW config dir '{{ dsw_config_dir }}'"
  ansible.builtin.file:
    path: "{{ dsw_config_dir }}"
    state: absent
  tags:
    - clean
    - dsw-clean

# Clean MinIO Backup

- name: "Clean MinIO outside-container backup dir '{{ dsw_minio_backup_dir_outside }}'"
  ansible.builtin.file:
    path: '{{ dsw_minio_backup_dir_outside }}'
    state: absent
  tags:
    - dsw-clean-backups

- name: Clean Cron DSW backup-minio script
  ansible.builtin.cron:
    name: dws_backup_minio
    state: absent
    special_time: hourly
    # job: "{{ dsw_config_dir }}/backup-minio.sh >/dev/null"
  tags:
    - dsw-clean-cron

# Clean Postgres Backup

- name: Clean Postgres outside-container backup dir '{{ dsw_postgres_backup_dir_outside }}'
  ansible.builtin.file:
    path: '{{ dsw_postgres_backup_dir_outside }}'
    state: absent
  tags:
    - dsw-clean-backups

  # NOTE system role task?
- name: Clean Cron DSW backup-postgres script
  ansible.builtin.cron:
    name: dws_backup_postgres
    state: absent
    special_time: hourly
    job: "{{ dsw_config_dir }}/backup-postgres.sh"
  tags:
    - dsw-clean-cron
