
- name: Update DSW app config file
  template:
    dest:  "{{ dsw_conf_dir }}/dsw.yml"
    src:   "dsw.yml.j2"
    owner: "root"
    group: "root"
    mode: "u=rw,go="

- name: Update DSW integration config file
  template:
    dest:  "{{ dsw_conf_dir }}/integration.yml"
    src:   "dsw-integration.yml.j2"
    owner: "root"
    group: "root"
    mode: "u=rw,go="

- name: Configure DSW client
  copy:
    src:   "files/dsw-client/"
    dest: "{{ dsw_conf_dir }}/dsw-client/"
    owner: "root"
    group: "root"
    mode: "u=rwX,go=rX"
    force: yes

- name: Configure DSW mailer
  copy:
    src:   "files/dsw-mailer/"
    dest: "{{ dsw_conf_dir }}/dsw-mailer/"
    owner: "root"
    group: "root"
    mode: "u=rwX,go=rX"
    force: yes

# TODO
  # - name: Update DSW create-bucket script
  #   template:
  #     dest:  "{{ dsw_conf_dir }}/create-bucket.sh"
  #     src:   "dsw-create-bucket.sh.j2"
  #     owner: "root"
  #     group: "root"
  #     mode: "u=rwx,go="

  # - name: Create DSW bucket
  #   shell: "{{ dsw_conf_dir }}/create-bucket.sh"
  #   register: command_result
  #   changed_when:
  #     - command_result.rc == 0
  #     - '"Your previous request to create the named bucket succeeded and you already own it." not in command_result.stderr'
  #   failed_when:
  #     - command_result.rc != 0
  #     - '"Your previous request to create the named bucket succeeded and you already own it." not in command_result.stderr'

- name: "Have MinIO outside-container backup dir '{{ dsw_minio_backup_dir_outside }}'"
  file:
    path: '{{ dsw_minio_backup_dir_outside }}'
    state: directory
    owner: "root"
    group: "root"
    mode: "u=rwx,go="

- name: Update DSW backup-minio script
  template:
    dest:  "{{ dsw_conf_dir }}/backup-minio.sh"
    src:   "dsw-backup-minio.sh.j2"
    owner: "root"
    group: "root"
    mode: "u=rwx,go="

# NOTE presunout do system?
- name: Let Cron to run DSW backup-minio script hourly
  cron:
    name: dws_backup_minio
    state: present
    special_time: hourly
    job: "{{ dsw_conf_dir }}/backup-minio.sh >/dev/null"

- name: Have Postgres outside-container backup dir '{{ dsw_postgres_backup_dir_outside }}'
  file:
    path: '{{ dsw.postgres_backup_dir_outside }}'
    state: directory
    owner: "root"
    group: "root"
    mode: "uo=rwx,g="

- name: Update DSW backup-postgres script
  template:
    dest:  "{{ dsw_conf_dir }}/backup-postgres.sh"
    src:   "dsw-backup-postgres.sh.j2"
    owner: "root"
    group: "root"
    mode: "u=rwx,go="

- name: Let Cron to run DSW backup-postgres script hourly
  cron:
    name: dws_backup_postgres
    state: present
    special_time: hourly
    job: "{{ dsw_conf_dir }}/backup-postgres.sh"
