# DOCKER-COMPOSE TODO: nahradit za ansible "mendelu-container-role"
- name: Configure docker-compose
  ansible.builtin.template:
    src: dsw-docker-compose.yml.j2
    dest: "{{ dsw_config_dir }}/docker-compose.yml"
    owner: "root"
    group: "root"
    mode: "u=rwx,go="
  tags:
    - composer
