# Inicializace aplikace
# - nastavi noveho interniho admina, odstrani defaultni uzivatele,
#   nastavi dalsi interni uzivatele (pokud neexistuji)
# - vytvori minio bucket
# @required_vars: [dsw_internal_admins, dsw_default_users, dsw_internal_users]

- name: init | Set internal admin
  ansible.builtin.set_fact:
    __dsw_user_create: "{{ dsw_users_internal_admin }}"

- name: init | Create internal admin
  ansible.builtin.include_tasks: user_create.yml

- name: init | Renew token for internal admin
  ansible.builtin.include_tasks: get_api_token.yml

- name: init | Remove default users
  ansible.builtin.include_tasks: user_delete.yml
  loop: "{{ dsw_default_users }}"
  loop_control:
    loop_var: __dsw_user_delete
    label: "{{ __dsw_user_delete.email }}"

- name: init | Create other internal users
  ansible.builtin.include_tasks: user_create.yml
  loop: "{{ dsw_internal_users }}"
  loop_control:
    loop_var: __dsw_user_create
    label: "{{ __dsw_user_create.email }}"
