# Odstrani DSW config adresar, adresar se skripty, cron joby,
# data Postgresu a S3 (MinIO), pokud je nastaven `CLEAN_DATA`
# a backupy Postgresu a S3 (MinIO), ookud je nastaven `CLEAN_DATA_BACKUP`

- name: Check variables
  ansible.builtin.assert:
    that:
      - dsw_config_dir is defined
      - dsw_script_dir is defined
      - dsw_minio_data_dir is defined
      - dsw_minio_backup_dir is defined
      - dws_minio_backup_cronjob_name is defined
      - dsw_postgres_data_dir is defined
      - dsw_postgres_backup_dir is defined
      - dws_postgres_backup_cronjob_name is defined
      - "CLEAN_DATA is not defined or CLEAN_DATA in ['ALL', 'MINIO', 'POSTGRES']"
      - "CLEAN_DATA_BACKUP is not defined or CLEAN_DATA_BACKUP in ['ALL', 'MINIO', 'POSTGRES']"

# MinIO
- name: Clean Cron DSW backup-minio script
  ansible.builtin.cron:
    name: "{{ dws_minio_backup_cronjob_name }}"
    state: absent
    special_time: hourly
    # job: "{{ dsw_script_dir }}/backup-minio.sh >/dev/null"

- name: "Clean MinIO data dir '{{ dsw_minio_data_dir }}'"
  ansible.builtin.file:
    path: '{{ dsw_minio_data_dir }}'
    state: absent
  when: "CLEAN_DATA is defined and CLEAN_DATA in ['ALL', 'MINIO']"

- name: "Clean MinIO backup dir '{{ dsw_minio_backup_dir }}'"
  ansible.builtin.file:
    path: '{{ dsw_minio_backup_dir }}'
    state: absent
  when: "CLEAN_DATA is defined and CLEAN_DATA in ['ALL-BACKUP', 'MINIO-BACKUP']"

# Postgres
- name: Clean Cron DSW backup-postgres script
  ansible.builtin.cron:
    name: "{{ dws_postgres_backup_cronjob_name }}"
    state: absent
    special_time: hourly
    # job: "{{ dsw_script_dir }}/backup-postgres.sh"

- name: "Clean Postgres data'{{ dsw_postgres_data_dir }}'"
  ansible.builtin.file:
    path: "{{ dsw_postgres_data_dir }}"
    state: absent
  when: "CLEAN_DATA is defined and CLEAN_DATA in ['ALL', 'POSTGRES']"

- name: Clean Postgres backup dir '{{ dsw_postgres_backup_dir }}'
  ansible.builtin.file:
    path: '{{ dsw_postgres_backup_dir }}'
    state: absent
  when: "CLEAN_DATA is defined and CLEAN_DATA in ['ALL-BACKUP', 'POSTGRES-BACKUP']"

# DSW
- name: "Clean DSW config dir '{{ dsw_config_dir }}'"
  ansible.builtin.file:
    path: "{{ dsw_config_dir }}"
    state: absent

- name: "Clean DSW script dir '{{ dsw_script_dir }}'"
  ansible.builtin.file:
    path: "{{ dsw_script_dir }}"
    state: absent
