# Ziskani tokenu pro pristup k DSW API
# Pokud se nepodari ziskat token z lokalniho admina,
# zkusi ziskat token pres defaultniho admina (albert.einstein@example.com)
# Token vraci do promenne "{{ __dsw_api_token }}"
# Pri nastaveni globalniho tagu "DEBUG" vypise token do konzole
# @required_vars: dsw_api_url, dsw_internal_admin, dsw_default_admin

- name: "get_api_token | Try to getting DSW API token from the local admin '{{ dsw_users_internal_admin.email }}'"
  ansible.builtin.uri:
    url: "{{ dsw_api_url }}/tokens"
    method: POST
    status_code: 201
    body_format: json
    body:
      email: "{{ dsw_users_internal_admin.email }}"
      password: "{{ dsw_users_internal_admin.password }}"
  register: __dsw_api_response
  failed_when: false

- name: "get_token | Set DSW API token from the local admin '{{ dsw_internal_admin.email }}'"
  ansible.builtin.set_fact:
    __dsw_api_token: "{{ __dsw_api_response.json.token }}"
  when: __dsw_api_response.json.token is defined

- name: "get_token | Try to getting DSW API token from the default admin '{{ dsw_default_admin.email }}'"
  ansible.builtin.uri:
    url: "{{ dsw_api_url }}/tokens"
    method: POST
    status_code: 201
    body_format: json
    body:
      email: "{{ dsw_default_admin.email }}"
      password: "{{ dsw_default_admin.password }}"
  when: __dsw_api_token is not defined
  register: __dsw_api_response

- name: "get_api_token | Set DSW API token from the default user '{{ dsw_default_admin.email }}'"
  ansible.builtin.set_fact:
    __dsw_api_token: "{{ __dsw_api_response.json.token }}"
  when: __dsw_api_response.json.token is defined

- name: "[DEBUG] get_token | Got DSW API token"
  ansible.builtin.debug:
    msg: "Bearer {{ __dsw_api_token }}"
  when: DEBUG is defined
