- set_fact:
    dsw_action: create
  when: dsw_action is not defined

- set_fact:
    all_components: "{{ ansible_run_tags| intersect(['minio', 'postgres', 'dsw_server']) == [] }}"


- block:
  - debug: msg="{{ dsw_action }} minio"
    when: "'minio' in ansible_run_tags or all_components"
    # tags:
    #   - minio

  - debug: msg="{{ dsw_action }} postgres"
    when: "'postg' in ansible_run_tags or all_components"
    # tags:
    #   - postgres
