- name: Include tasks '{{ dsw_action }}'
  ansible.builtin.include_tasks: "dsw_{{ dsw_action }}.yml"
  when: dsw_action is defined

- name: Include default action tasks
  when: dsw_action is not defined
  block:
    - name: Include tasks
      ansible.builtin.include_tasks: "dsw_configure.yml"
    - name: Include tasks
      ansible.builtin.include_tasks: "dsw_init.yml"
    - name: Include tasks
      ansible.builtin.include_tasks: "dsw_start.yml"
