- block:
    - name: Configure DSW Application
      ansible.builtin.include_tasks: config.yml
  tags:
    - config
  # notify:
  #   - containers.restart

# - block:
#     - name: Start DSW Appcication
#       ansible.builtin.include_role:
#         name: containers
#         vars:
#           containers_applicatinon: "{{ dsw_container_app }}"
#           containers_state: started
#   tags:
#     - containers

# - name: Init DSW Application
#   ansible.builtin.include_tasks: init.yml
#   tags:
#     - init
#   notify:
#     - containers.restart
