- name: Stop Minio Container
  containers.podman.podman_container:
    name: "{{ dsw_minio_container_name }}"
    state: stoped
  when: dsw_minio_container_name is defined
  tags: 
    - never
    - stop
    - restart
    - destroy
    - minio_stop
    - minio_destroy
    - minio_restart

- name: Destroy Minio Container
  containers.podman.podman_container:
    name: "{{ dsw_minio_container_name }}"
    state: absent
  when: dsw_minio_container_name is defined
  tags:
    - never
    - destroy
    - minio_destroy
  
- name: Create Minio Container
  containers.podman.podman_container:
    name: "{{ dsw_minio_container_name }}"
    image: "{{ dsw_minio_container_image }}"
    ports: "{{ dsw_minio_container_ports }}"
    env:
    volumes:
      - db-data:/var/lib/postgresql/data
    when:
    tags:
      - never
      - stop
      - restart
      - destroy
      - minio_stop
      - minio_destroy
      - minio_restart
   