# Odstrani interniho uzivatele
# @required_vars: [__dsw_user_delete, dsw_api_url]
# @optional_vars: [__dsw_api_token]

- name: "user_delete | Get API token if necessary"
  ansible.builtin.include_tasks: get_api_token.yml
  when: dsw_api_token is not defined

- name: "user_delete | Set __dsw_user_email"
  ansible.builtin.set_fact:
    __dsw_user_email: "{{ __dsw_user_delete.email }}"

- name: "user_delete | Get user UUID"
  ansible.builtin.include_tasks: user_get.yml

- name: "user_delete | Delete user {{ __dsw_user.email }}"
  ansible.builtin.uri:
    url: "{{ dsw_api_url }}/users/{{ __dsw_user.uuid }}"
    method: DELETE
    status_code: 204
    headers:
      Authorization: "Bearer {{ __dsw_api_token }}"
  register: __dsw_api_response
  when: __dsw_user.uuid is defined
  changed_when: true

- name: "DEBUG | Got DSW API response"
  ansible.builtin.debug:
    var: __dsw_api_response
  when: "'DEBUG' in ansible_run_tags"
