- name: DSW
  hosts: dsw
  become: true

  tasks:
    - name: Clean up old files
      ansible.builtin.import_role:
        name: mendelu.dsw.dsw
        tasks_from: dsw_clean
      tags: [clean]

    - name: Configure DSW
      ansible.builtin.import_role:
        name: mendelu.dsw.dsw
        tasks_from: dsw_configure
      tags: [configure]

    - name: Configure Reverse Proxy
      ansible.builtin.import_role:
        name: nginx-reverse-proxy
        tasks_from: proxy_configure
      tags: [proxy, configure]
