- name: DSW
  hosts: dswservers
  become: true
  vars:
    project:
      name: DSW
      description:
      server:
        cpu: 4
        ram_gb: 8
  vars_files:
    - vars/config-dsw.yml
    - vars/config-containers.yml

  roles:
    # - { role: mendelu.oit.project }
    - { role: dsw, tags: [dsw]}
    - { role: containers, tags: [containers]}
