- name: DSW
  hosts: dswservers
  vars:
    project:
      name: DSW
      description:
      server:
        cpu: 4
        ram_gb: 8 
  vars_files:
    - vars/config-dsw.yml

  roles:
    # - { role: mendelu.oit.project }
    - { role: dsw }
 