- name: Install System
  hosts: dswhost
  become: true
  roles:
    - role: mendelu.infra.system
    # - role: mendelu.infra.containers
    # - role: mendelu.infra.firewall
    # - role: mendelu.infra.email
  tags: system

- name: Install DSW Application
  # all instances, use --limit to limit to specific instance
  hosts: dswapp
  become: true
  roles:
    - role: mendelu.dsw.dsw
  tags: dsw

- name: Install Reverse Proxy
  hosts: dswhost
  become: true
  roles:
    - role: mendelu.infra.reverse_proxy
  tags: proxy
