- name: DSW install
  hosts: dswservers
  become: true
  vars_files:
    - vars/config-system.yml
    - vars/config-dsw.yml
    - vars/config-proxy.yml
    - vars/config-users.yml

  roles:
    # Config local system role (AlmaLinux)
    # in-role-tags: hostname, timezone, packages, users, groups, and TODO many others
    - { role: mendelu.infra.system, tags: system }

    # DSW App
    # in-role-tags: minio, postgres, dsw-server, dsw-mailer, dsw-client, dsw-docworker
    # - setup
    - { role: nginx-reverse-proxy, tags: proxy }
    - { role: dsw, tags: dsw }
    # - control
    # - { role: dsw, tags: [never, backup], dsw_action: backup }
    # - { role: dsw, tags: [never, stop, restart, destroy], dsw_action: stop }
    # - { role: dsw, tags: [never, start, restart], dsw_action: start }
    # - { role: dsw, tags: [never, destroy], dsw_action: destroy }

    # # TODO
    # # monitoring
    # - { role: prom-node-exporter, tags: [ monitoring ] }
