---
- name: Kopírování SSL souborů
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/nginx/ssl/"
    mode: '0644'
  loop:
    - "key-dsw.mendelu.cz.pem"
    - "cert-dsw.mendelu.cz.pem"
    - "ca-geant.pem"
  tags:
    - config
    - certs

- name: Vytvoření NGINX konfiguračního souboru z šablony
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    mode: '0644'
  tags:
    - config
    - nginx

- name: Spuštění NGINX kontejneru s Podmanem
  community.docker.docker_container:
  # containers.podman.podman_container:
    name: nginx_reverse_proxy
    image: nginx:latest
    state: started
    recreate: true
    published_ports:
      - "443:443"
    volumes:
      - "/etc/nginx/ssl:/etc/nginx/ssl:ro,z"
      - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z"
  tags:
    - config
    - nginx
