- name: Set environment var from shell
  ansible_bultin.set_fact:
    xenv: "{{ lookup('xenv', 'ENVIRONMENT', default=undef()) }}"
  when: xenv is not defined
  delegate_to: localhost

- name: Fail if iac_environment is not set
  ansible.builtin.fail:
    msg:
      The `environment` variable is not set!
      Please set it before running this playbook.
      Or you can set it as the `ENVIRONMENT` shell variable.
  when: xenv is not defined
